FROM ubuntu:latest

COPY ./target/maven-jlink/default/ /usr/app/
COPY ./NWTiS_04_tvrtka.txt /usr/app/
COPY ./kartaPica.json /usr/app/
COPY ./kuhinja_1.json /usr/app/
COPY ./kuhinja_2.json /usr/app/
COPY ./kuhinja_3.json /usr/app/

WORKDIR /usr/app

EXPOSE 8000

CMD ["bin/java", "-m", "ibeusan20_vjezba_06_tvrtka/edu.unizg.foi.nwtis.ibeusan20.vjezba_06.PosluziteljTvrtka", "NWTiS_04_tvrtka.txt"]
