FROM eclipse-temurin:23-jre

COPY ./target/ibeusan20_vjezba_06_tvrtka-1.1.0.jar /usr/app/
COPY ./target/libs /usr/app/libs
COPY ./NWTiS_04_tvrtka.txt /usr/app/
COPY ./kartaPica.json /usr/app/
COPY ./kuhinja_1.json /usr/app/
COPY ./kuhinja_2.json /usr/app/
COPY ./kuhinja_3.json /usr/app/

WORKDIR /usr/app

EXPOSE 8000

CMD ["java", "-jar", "ibeusan20_vjezba_06_tvrtka-1.1.0.jar", "NWTiS_04_tvrtka.txt"]
