CREATE USER nwtis_2 PASSWORD 'nwtis#2';

DROP USER nwtis2;

SELECT * FROM INFORMATION_SCHEMA.USERS;

SELECT * FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES;

CREATE USER nwtis_2 PASSWORD 'nwtis#2';

ALTER USER nwtis_2 SET PASSWORD 'nwtis#2';

DROP TABLE DNEVNIK_RADA;

create table dnevnik_Rada (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	vrijeme timestamp,
	korisnickoIme char (20),
	adresaRacunala varchar (99),
	ipAdresaRacunala varchar (50),
	nazivOS varchar (30),
	verzijaVM varchar (20),
	opisRada varchar (512)
); 

SELECT * FROM dnevnik_Rada;

CREATE ROLE aplikacija;

DROP ROLE aplikacija;

GRANT aplikacija TO nwtis_2;

GRANT SELECT, UPDATE, INSERT ON TABLE dnevnik_Rada TO aplikacija;
